spring.application.name=portalku
spring.profiles.active=dev

app.name=Portal Jurnal PSDKU Lumajang
app.version=0.1.0
app.max-item=50

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.operations-sorter=method